config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users
    root to: "home#index"
    resources :users
    resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    attachment :image
    
    with_options presence: true do
        validates :title
        validates :body
        validates :image
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image 
  has_many :posts, dependent: :destroy
  
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    private
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts=Post.all.order(id: "DESC")

  end
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @posts=Post.all.order(id: "DESC")
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post=Post.new
  end
  
  def create
    @post=Post.new(post_params)
    @post.user_id=current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "  投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
    @post=Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: "  不正なアクセスです。"
    end
  end
  
  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "  更新に成功しました。"
    else
      render :edit
    end
  end
  
  def destroy
    post=Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "  投稿を削除しました。"
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです。"
    end
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "  更新に成功しました。"
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
 <section>
  <div class="container">

    <% @posts.each do |post| %>
    <div class="feed_post">
     <div>
       <figure>
         <%= link_to post_path(post) do %>
           <%= attachment_image_tag post, :image, class: "feed_photo"  %>
         <% end %>
        </figure>
      </div>


         <div>
             <figure class="image_area">
                 <%= link_to user_path(post.user.id) do %>
                    <%= attachment_image_tag post.user, :profile_image, fallback: "default.png", class: "feed_userimg" %>
                 <% end %>
              </figure>
         </div>
                  
                  <div class="feed_username">
                      <%= link_to post.user.username, user_path(post.user), class: "nm" %>
                  </div>
                
                
                
                 <div class="feed_right">
                  <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
                 </div>
                
            </div>
          <% end %>
         
      </div>
   </section>




 
<% else %>


   <div class="before_login">
     <ul id="top">  
      <li>
      <img class="home-logo" src="/assets/home-logo.png">
     </li>
                
     <li>
         <%= link_to new_user_registration_path do %>
        <button class="signin">アカウント作成</button>
         <% end %>
     </li>
     
     <li> 
        <%= link_to new_user_session_path do %>
        <button class="login">ログイン</button>
        <% end %>
     </li>
     
     <li class="look">
       <%= link_to '投稿をみる', root_path(anchor:'promptposts') %>
     </li>
     
    </ul>



<section>
  <div class="prompt-posts" id="promptposts">
   
    <% @posts.each do |post| %>
    
    
    <div class="feed_post">
     <div>
       <figure>
         <%= link_to root_path(anchor:'top') do %>
           <%= attachment_image_tag post, :image, class: "feed_photo"  %>
         <% end %>
        </figure>
      </div>


         <div>
             <figure class="image_area">
                 <%= link_to root_path(anchor:'top') do %>
                    <%= attachment_image_tag post.user, :profile_image, fallback: "default.png", class: "feed_userimg" %>
                 <% end %>
              </figure>
         </div>
                  
                  <div class="feed_username">
                      <%= link_to post.user.username, root_path(anchor:'top'), class: "nm" %>
                  </div>
                
                
                
                 <div class="feed_right">
                  <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
                 </div>
             </div> 
             
            
          <% end %>
     
      </div> 
    </section>
    
</div>    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo up</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/41c3351b4c.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
       <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    
    <% if flash[:alert] %>
     <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
     </div>
    <% end %>
 
<!-- ナビゲーション -->

    <nav>
     <div class="space-between"> 
      <div>
        <%= link_to root_path do %>
         <img class="nav-logo" src="/assets/navigation-logo.png">
        <% end %>
      </div>
      
      <div>
       <% if user_signed_in? %>
      
            <ul class="nav-icons">
                 <li class="switching torio">
                    <%= link_to posts_path do %>
                       <i class="fas fa-globe nav_icon"></i>
                    <% end %>
                 </li>
                
                 <li class="switching torio">
                  <%= link_to new_post_path do %>
                        <i class="far fa-plus-square nav_icon"></i>
                  <% end %>
                 </li>
                    
                 <li class="switching torio">
                   <%= link_to users_path do %>
                      <i class="fas fa-users nav_icon"></i>
                   <% end %>
                 </li>
        
                 <li class="switching">
                     <%= link_to user_path(current_user) do %>
                    　<i class="fas fa-house-user nav_icon last-icon"></i>
                    <% end %>
                  </li>  
             </ul>
          </div>
        </div>
        
        <input class="none" type="checkbox" id="check">
         <label for="check">
          <i class="fas fa-bars" id="berger"></i>
          <i class="fas fa-window-close" id="cancel"></i>
         </label>
                 
                 <div class="dropdown-menu"> 
                   <ul>
                       <li class="posts-stage">
                    　　　<%= link_to posts_path do %>
                              <p>投稿を見る</p>
                    　　　<% end %>
                 　　　</li>
                 　　　
                 　　　<li class="user-stage">
                 　　    　  <%= link_to user_path(current_user) do %>
                    　　　　　　　<p>マイページ</p>   
                          <% end %>
                        </li>
                        
                        <li class="new-post-stage">
                            <%= link_to new_post_path do %>
                       　　　     <p>投稿する</p>
                            <% end %>
                        </li>
                       
                       <li class="users-stage">
                            <%= link_to users_path do %>
                               <p>ユーザーページ</p>
                            <% end %>
                       </li>
                       
                       <div class="border_logout"></div>
                       
                       <li class="logout-stage">
                            <%= link_to destroy_user_session_path, method: :delete do %>
                            　<p>ログアウト</p>
                            <% end %>
                        </li>
                   </ul>
                 </div>
        
        </nav>
                
        
        
             
               
         <% end %>
    </div>
      
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
   <div class="errordisplay">
    <h2><%= pluralize(@post.errors.count, "error")%>prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class = "container">
    <div class = "form_card">
        
        <div class = "subject">
　　        <p>投稿編集</p>
　　    </div>

        <%= form_for @post do |f| %>

        <div class="form-group">
            <%= f.text_field :title, class: "post_form post_title", placeholder: "タイトルを入力" %>
        </div> 
        
        <div class="form-group">
            <%= f.text_area :body, class: "post_form post_content", placeholder: "内容を入力" %>
        </div>
    
        <div>
            <%= f.attachment_field :image, class: "image_field" %>
        </div>
        
        <div>
            <%= f.submit "編集", class: "submit_btn" %>
        </div>
        <% end %>
     </div>
  </div>

app/views/posts/index.html.erb
<section>
  <div class="container">
    
     <% @posts.each do |post| %>
        <div class="feed_post">
     
          <div>
            <figure>
             <%= link_to post_path(post) do %>
              <%= attachment_image_tag post, :image, class: "feed_photo" %>
             <% end %>
            </figure>
          </div>
          
           
                <div>
                  <figure class="image_area">
                   <%= link_to user_path(post.user.id) do %>
                    <%= attachment_image_tag post.user, :profile_image, fallback: "default.png", class: "feed_userimg" %>
                   <% end %>
                  </figure>
                  </div>
                  
                  <div class="feed_username">
                      <%= link_to post.user.username, user_path(post.user), class: "nm" %>
                  </div>
                
                
                
                 <div class="feed_right">
                  <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
                 </div>
                
            </div>
          <% end %>
         
      </div>
   </section>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
<div class="errordisplay">
     <h2><%= pluralize(@post.errors.count, "error")%>prohibited this object from being saved: not successfully</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class = "container">
    <div class = "form_card">
        
　　    <div class = "subject">
　　        <p>新規投稿</p>
　　    </div>
　　    
        <%= form_for @post do |f| %>
    
    
    <div class="form-group">
        <%= f.text_field :title, class: "post_form post_title", placeholder: "タイトルを入力" %>
    </div>  

    <div class="form-group">
        <%= f.text_area :body, class: "post_form post_content", placeholder: "内容を入力" %>
    </div> 

  <div>
      
      <%= f.attachment_field :image, class: "image_field" %>
  </div>
  
  <div>
      <%= f.submit "投稿", class: "submit_btn" %>
  </div>
  <% end %>
 </div>
</div>
    

app/views/posts/show.html.erb
<div class="show_post">
    
     
        <div>
          <figure class="posted_user_img">
           <%= link_to user_path(@post.user.id) do %>
            <%= attachment_image_tag @post.user, :profile_image, fallback: "default.png", class: "user_small_img" %>
           <% end %>
          </figure>
        </div>
  
        <div class="posted_user_name"> 
            
              <%= link_to user_path(@post.user), class: "postuser_name" do %>
               <%= @post.user.username %>
              <% end %>
             
        </div>
      
    

          <div class="show_posted_photo_div">
              <figure>
                <%= attachment_image_tag @post, :image, class: "show_posted_photo" %>
              </figure>
          </div>
          
          
          
     <div class="string"> 
     
           <div class="posted_title">
             <%= @post.title %>
           </div>

           <div class="posted_content">
             <%= simple_format @post.body %>
           </div>
           
     </div>
     
         <div class="posted_time">
           <time><%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
        </div>

     
      <div>
        <% if @post.user.id == current_user.id %>
             
             <%= link_to edit_post_path(@post) do %>
                 <button class="edit_button">編集</button>
             <% end %>
        <% end %>
      </div>
      
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, "error")%>prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <div class="container">
    <div class="left">
      <h2>ユーザー編集</h2>
      
        <%= form_for @user do |f| %>
        
          <div class="useredit_field">
            <%= f.label :username, "ユーザー名", class: "label" %><br />
            <%= f.text_field :username, class: "entry_field" %>
          </div>

          <div class="useredit_field">
            <%= f.label :email, "メールアドレス", class: "label" %><br />
            <%= f.email_field :email, class: "entry_field" %>
          </div>

          <div class="useredit_field">
            <%= f.label :profile, "プロフィール", class: "label" %><br />
            <%= f.text_area :profile, class: "entry_field_big" %>
          </div>

          <div class="useredit_field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %><br />
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>
          
          <div class="useredit_btn">
          <%= f.submit "更新", class: "btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="user_cards">
    
        <% @users.each do |user| %>
        <div class="card">
            <div class="userimg">
                <%= link_to user_path(user) do %>
                 <%= attachment_image_tag user, :profile_image, fallback: "default.png", width: "135", height: "135", class: "user_img" %>
                <% end %>
            </div>
         
            <div class="username">
                 <%= link_to user.username, user_path(user), class: "user_name" %>
            </div>
            
            <div>
            <%= link_to user_path(user) do %>
                <button class="for_user_btn">プロフィールを見る</button>
            <% end %>
            </div>
            
         </div>
        <% end %>
           
</div>  
      

app/views/users/show.html.erb
    <div class="user_profile_field">       
            <figure class="image__field">
             <%= attachment_image_tag @user, :profile_image, fallback: "default.png", class: "profile_img usershowimg" %>
            </figure>
          
                <div class="name_field">
                  <strong><%= @user.username %></strong>
                </div>
                
                <div class="profile_field">
                   <%= @user.profile %>
                </div>
                
                <% if @user.id == current_user.id %>
              
                <div class="edit_btn_field">
                    <%= link_to "編集", edit_user_path(@user), class: "user_edit_button" %>
                </div>
                <% end %>
              
        <hr class="priod"></hr>            
    </div>

            
          

<section class="section">
  
 <div class="position">  
    
      <% @user.posts.each do |post| %>
        <div class="post_card">
            
              <figure class="posted_photo">
                <%= link_to post_path(post) do %>  
                 <%= attachment_image_tag post, :image, class: "photo_image" %>
                <% end %>
              </figure>
              
              <div class="content">
              <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
              </div>
              
            
        
                
          
          <div class="current_user_only">      
          <% if @user.id == current_user.id %>
                  
                  
               <%= link_to edit_post_path(post), class: "panel-block" do %>
                  <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                  </span>
               <% end %>
  
              
               <%= link_to post_path(post), method: :delete, deta: {confirm: "削除しますか？"}, class: "panel-block" do %>
                 <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                 </span>
               <% end %>

          <% end %>
          </div>
          
          　<div class="for_show_page">
              <%= link_to post_path(post) do %>
                  <button class="btn_imgg">投稿を見る</button>
              <% end %>
            </div>
          
            
        </div>
      <% end %>
      
       </div>
      
</section>
    
 